docs: remove fail for below 80%, just warn

diff --git a/.github/workflows/audired-tookit.yml b/.github/workflows/audired-tookit.yml
--- a/.github/workflows/audired-tookit.yml
+++ b/.github/workflows/audired-tookit.yml
@@ -163,8 +163,9 @@ jobs:
         
                 # Fail the job if the average coverage is below 80%
                 if (( $(echo "$AVERAGE_COVERAGE < 80" | bc -l) )); then
-                  echo "Average coverage is below 80%. Failing the job."
-                  exit 1
+                    echo "Average coverage is below 80%. Please raise test threshold."
+                    #   echo "Average coverage is below 80%. Failing the job."
+                    #   exit 1
                 fi
 
     # dependency_sync:
